server:
  port: 8081
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
spring:
  mvc:
    favicon:
      enabled: false
  jackson:
    time: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    mongodb:
      uri: mongodb://danmu:danmu@39.108.110.44:27017/dm
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    druid:
      url: jdbc:mysql://39.108.110.44:3306/ys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: ys
      password: hjj225
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 39.108.110.44
    password: danbai225
    port: 6379
    timeout: 1000
mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mapper/*.xml

